# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      
      # Generates a BoM and uploads it to OWASP Dependency Track
      - name: Generates BoM and upload to OWASP DTrack
        id: riskscoreFromDT
        uses:  CycloneDX/gh-node-module-generatebom@v1.0.0
        with:
          # cyclonedx-bom -o bom.xml
           # url: 'http://localhost:8081'
           # key: 'wh2ETYrJv0xmwP6R9MzhxIZqtgvTTlIp'
           #language: 'nodejs'
           path: "./"
           output: ./bom.xml
     #Uploading  bom  
      - name: Upload BOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v1.0.0
        with:
          serverhostname: 'http://localhost:8080'
          apikey: ${{ secrets.wh2ETYrJv0xmwP6R9MzhxIZqtgvTTlIp }}
          projectname: 'ssabomupload'
          projectversion: '1.0'
    
      
      # Show the risk score output 
      - name: Get the output time
        run: echo "The risk score of the project is ${{ steps.riskscoreFromDT.outputs.riskscore }}"
        
      - run: npm install
      - run: npm run build
